In [38]:
import numpy as np
import pandas as pd

In [39]:
arr=np.random.randint(0,10,size=(5))
arr

array([1, 4, 8, 0, 3])

In [40]:
arr>2

array([False,  True,  True, False,  True])

In [41]:
arr[0]=10

In [42]:
arr2=np.random.randint(0,10,size=(5,6))
arr2

array([[4, 5, 3, 9, 1, 4],
       [9, 2, 3, 2, 7, 3],
       [4, 9, 2, 9, 3, 8],
       [5, 8, 7, 7, 7, 1],
       [4, 3, 0, 3, 4, 0]])

In [43]:
arr2[:,[0,1]]

array([[4, 5],
       [9, 2],
       [4, 9],
       [5, 8],
       [4, 3]])

In [44]:
arr2[2,1]=100
arr2

array([[  4,   5,   3,   9,   1,   4],
       [  9,   2,   3,   2,   7,   3],
       [  4, 100,   2,   9,   3,   8],
       [  5,   8,   7,   7,   7,   1],
       [  4,   3,   0,   3,   4,   0]])

In [45]:
df=pd.DataFrame(data=arr2,columns=list('ABCDEF'))
df

A    B  C  D  E  F
0  4    5  3  9  1  4
1  9    2  3  2  7  3
2  4  100  2  9  3  8
3  5    8  7  7  7  1
4  4    3  0  3  4  0