In [1]:
import numpy as np
import pandas as pd

In [2]:
arr=np.random.randint(0,10,size=(5))
arr

array([4, 9, 5, 4, 6])

In [3]:
arr>2

array([ True,  True,  True,  True,  True])

In [4]:
arr[0]=10

In [5]:
arr2=np.random.randint(0,10,size=(5,6))
arr2

array([[1, 8, 9, 7, 7, 2],
       [3, 4, 8, 5, 5, 5],
       [7, 4, 6, 9, 3, 7],
       [7, 0, 2, 9, 1, 4],
       [4, 0, 1, 0, 6, 5]])

In [6]:
arr2[:,[0,1]]

array([[1, 8],
       [3, 4],
       [7, 4],
       [7, 0],
       [4, 0]])

In [7]:
arr2[2,1]=100
arr2

array([[  1,   8,   9,   7,   7,   2],
       [  3,   4,   8,   5,   5,   5],
       [  7, 100,   6,   9,   3,   7],
       [  7,   0,   2,   9,   1,   4],
       [  4,   0,   1,   0,   6,   5]])

In [8]:
import pandas as pd

df = pd.DataFrame(data=arr2, columns=list('ABCDEF'))



In [9]:
s=pd.Series(data=np.array([True,False,True]),index=list('ABC'))
s

A     True
B    False
C     True
dtype: bool

In [10]:
s['A':'B']#左闭右闭

A     True
B    False
dtype: bool

In [11]:
df

A    B  C  D  E  F
0  1    8  9  7  7  2
1  3    4  8  5  5  5
2  7  100  6  9  3  7
3  7    0  2  9  1  4
4  4    0  1  0  6  5

In [12]:
df.loc[0,'A']

1

In [13]:
df.loc[0]

A    1
B    8
C    9
D    7
E    7
F    2
Name: 0, dtype: int64

In [14]:
df.loc[:,['A','B']]

A    B
0  1    8
1  3    4
2  7  100
3  7    0
4  4    0

In [15]:
df[0:4]

A    B  C  D  E  F
0  1    8  9  7  7  2
1  3    4  8  5  5  5
2  7  100  6  9  3  7
3  7    0  2  9  1  4

In [16]:
df.loc[[1,2],['B','C']]

B  C
1    4  8
2  100  6

In [17]:
df.loc[[True,True,False,False,False]]

A  B  C  D  E  F
0  1  8  9  7  7  2
1  3  4  8  5  5  5

In [18]:
list=pd.Series(data=np.array([True,True,False,False,False]),index=[0,4,2,3,1,])
list

0     True
4     True
2    False
3    False
1    False
dtype: bool

In [19]:
df.loc[list]

A  B  C  D  E  F
0  1  8  9  7  7  2
4  4  0  1  0  6  5

In [20]:
df.loc[list]

A  B  C  D  E  F
0  1  8  9  7  7  2
4  4  0  1  0  6  5

In [21]:
df

A    B  C  D  E  F
0  1    8  9  7  7  2
1  3    4  8  5  5  5
2  7  100  6  9  3  7
3  7    0  2  9  1  4
4  4    0  1  0  6  5

In [22]:
df.iloc[:,0]  # Replace 'A' with any valid column label if needed

0    1
1    3
2    7
3    7
4    4
Name: A, dtype: int64

In [23]:
df.loc[:,'A']

0    1
1    3
2    7
3    7
4    4
Name: A, dtype: int64

In [24]:
df.iloc[[True,True,False,False,False]]

A  B  C  D  E  F
0  1  8  9  7  7  2
1  3  4  8  5  5  5

In [25]:
df.iloc[0:3]#隐式访问

A    B  C  D  E  F
0  1    8  9  7  7  2
1  3    4  8  5  5  5
2  7  100  6  9  3  7

In [26]:
df.loc[0:2]#显示访问

A    B  C  D  E  F
0  1    8  9  7  7  2
1  3    4  8  5  5  5
2  7  100  6  9  3  7

In [27]:
df.loc[0].loc['B']

8

In [28]:
df.loc[0,'B']

8

In [29]:
df.loc[:,'B'].iloc[2]

100

### 代码 `df.loc[:,'B'].iloc[2]` 的解释
这行代码对 DataFrame `df` 执行了两步操作：

1. `df.loc[:,'B']`：使用 `.loc` 访问器选择列 `'B'` 的所有行（`:`）。结果是一个包含列 `'B'` 值的 pandas Series。
2. `.iloc[2]`：对上述 Series 使用 `.iloc` 访问器，选择第三个位置（索引为 `2`，因为索引是从零开始的）的值。

总结：这段代码获取了 DataFrame 中列 `'B'` 的第三行的值。

### `iloc` 和 `loc` 的区别

1. **`iloc`（基于位置的索引）**：
   - 使用整数索引来访问数据。
   - 行和列的索引均为基于位置的整数索引（从 0 开始）。
   - 示例：`df.iloc[0, 1]` 表示获取第 0 行第 1 列的值。

2. **`loc`（基于标签的索引）**：
   - 使用行和列的标签（名称）来访问数据。
   - 行和列的索引可以是标签或布尔数组。
   - 示例：`df.loc[0, 'A']` 表示获取索引为 0 的行中列名为 `'A'` 的值。

总结：`iloc` 是基于位置的索引，而 `loc` 是基于标签的索引。

In [30]:
df['A']

0    1
1    3
2    7
3    7
4    4
Name: A, dtype: int64

In [31]:
df[['A','B']]

A    B
0  1    8
1  3    4
2  7  100
3  7    0
4  4    0

In [32]:
df[0:2]

A  B  C  D  E  F
0  1  8  9  7  7  2
1  3  4  8  5  5  5

In [33]:
df.loc[0:2,'A']

0    1
1    3
2    7
Name: A, dtype: int64