In [755]:
import pandas as pd
import numpy as np

Series

In [756]:
#pd.Series(data=None,index=None,dtype=None)
#data数据
#index索引
#dtype数据类型

In [757]:
pd.Series(np.arange(9))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

In [758]:
pd.Series(data=[1,2,3,4,5],index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [759]:
color_a=pd.Series({'red':10,'green':20,'biue':30})
color_a

red      10
green    20
biue     30
dtype: int64

Series属性

In [760]:
color_a.index

Index(['red', 'green', 'biue'], dtype='object')

In [761]:
color_a.values

array([10, 20, 30])

In [762]:
color_a[1]

/tmp/ipykernel_994/3888620981.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  color_a[1]


20

DataFrame

In [763]:
pd.DataFrame(data=None,index=None,columns=None)
#index行索引
#columns列索引

Empty DataFrame
Columns: []
Index: []

In [764]:
score=np.random.randint(40,100,(10,5))
score

array([[76, 99, 73, 99, 41],
       [53, 76, 65, 76, 53],
       [79, 98, 42, 87, 56],
       [51, 87, 43, 61, 82],
       [44, 44, 86, 61, 97],
       [85, 88, 40, 68, 81],
       [52, 72, 95, 82, 56],
       [78, 59, 77, 62, 80],
       [55, 44, 59, 65, 63],
       [62, 82, 41, 89, 97]])

In [765]:
score_df=pd.DataFrame(score)
score_df

0   1   2   3   4
0  76  99  73  99  41
1  53  76  65  76  53
2  79  98  42  87  56
3  51  87  43  61  82
4  44  44  86  61  97
5  85  88  40  68  81
6  52  72  95  82  56
7  78  59  77  62  80
8  55  44  59  65  63
9  62  82  41  89  97

In [766]:
score_df.shape

(10, 5)

In [767]:
subject=['语文','数学','英语','政治','体育']
stu=['同学'+str(i)for i in range(score_df.shape[0])]
data=pd.DataFrame(score,columns=subject,index=stu)
data

语文  数学  英语  政治  体育
同学0  76  99  73  99  41
同学1  53  76  65  76  53
同学2  79  98  42  87  56
同学3  51  87  43  61  82
同学4  44  44  86  61  97
同学5  85  88  40  68  81
同学6  52  72  95  82  56
同学7  78  59  77  62  80
同学8  55  44  59  65  63
同学9  62  82  41  89  97

`stu=['同学'+str(i)for i in range(score_df.shape[0])]` 创建了一个包含学生名称的列表。
列表中的每个元素是字符串 `'同学'` 加上从 0 到 `score_df.shape[0]-1` 的索引值。
例如，如果 `score_df` 有 10 行，则生成的列表为 `['同学0', '同学1', ..., '同学9']`。
这通常用于为数据框的行创建自定义索引。

`str(i)` 将整数 `i` 转换为字符串形式。
例如，如果 `i` 的值为 `5`，则 `str(i)` 的结果为 `'5'`。
这种转换通常用于将数字与字符串拼接或格式化输出。

属性

In [768]:
data.shape

(10, 5)

In [769]:
data.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [770]:
data.columns

Index(['语文', '数学', '英语', '政治', '体育'], dtype='object')

In [771]:
data.values

array([[76, 99, 73, 99, 41],
       [53, 76, 65, 76, 53],
       [79, 98, 42, 87, 56],
       [51, 87, 43, 61, 82],
       [44, 44, 86, 61, 97],
       [85, 88, 40, 68, 81],
       [52, 72, 95, 82, 56],
       [78, 59, 77, 62, 80],
       [55, 44, 59, 65, 63],
       [62, 82, 41, 89, 97]])

In [772]:
data.T

同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   76   53   79   51   44   85   52   78   55   62
数学   99   76   98   87   44   88   72   59   44   82
英语   73   65   42   43   86   40   95   77   59   41
政治   99   76   87   61   61   68   82   62   65   89
体育   41   53   56   82   97   81   56   80   63   97

In [773]:
data.head(5)#前5行

语文  数学  英语  政治  体育
同学0  76  99  73  99  41
同学1  53  76  65  76  53
同学2  79  98  42  87  56
同学3  51  87  43  61  82
同学4  44  44  86  61  97

In [774]:
data.tail(5)#后5行

语文  数学  英语  政治  体育
同学5  85  88  40  68  81
同学6  52  72  95  82  56
同学7  78  59  77  62  80
同学8  55  44  59  65  63
同学9  62  82  41  89  97

修改索引值

In [775]:
stu=['学生'+str(i)for i in range(score_df.shape[0])]
data.index=stu

In [776]:
data

语文  数学  英语  政治  体育
学生0  76  99  73  99  41
学生1  53  76  65  76  53
学生2  79  98  42  87  56
学生3  51  87  43  61  82
学生4  44  44  86  61  97
学生5  85  88  40  68  81
学生6  52  72  95  82  56
学生7  78  59  77  62  80
学生8  55  44  59  65  63
学生9  62  82  41  89  97

重设索引

reset_index(drop=False)


设置新的下标索引，drop:默认为False,不删除原索引，True，删除原索引

In [777]:
data.reset_index(drop=False)

index  语文  数学  英语  政治  体育
0   学生0  76  99  73  99  41
1   学生1  53  76  65  76  53
2   学生2  79  98  42  87  56
3   学生3  51  87  43  61  82
4   学生4  44  44  86  61  97
5   学生5  85  88  40  68  81
6   学生6  52  72  95  82  56
7   学生7  78  59  77  62  80
8   学生8  55  44  59  65  63
9   学生9  62  82  41  89  97

In [778]:
data.reset_index(drop=True)

语文  数学  英语  政治  体育
0  76  99  73  99  41
1  53  76  65  76  53
2  79  98  42  87  56
3  51  87  43  61  82
4  44  44  86  61  97
5  85  88  40  68  81
6  52  72  95  82  56
7  78  59  77  62  80
8  55  44  59  65  63
9  62  82  41  89  97

以某列值设置新索引

set_index(keys,drop=True)

keys:列索引名或列索引名称的列表
drop:默认为False,不删除原索引，True，删除原索引

In [779]:
df=pd.DataFrame({'month':[1,4,7,9],
                 'year':[2013,2014,2015,2016],
                 'sale':[55,33,234,56]})

In [780]:
df

month  year  sale
0      1  2013    55
1      4  2014    33
2      7  2015   234
3      9  2016    56

In [781]:
df.set_index('month')

year  sale
month            
1      2013    55
4      2014    33
7      2015   234
9      2016    56

In [782]:
df=df.set_index(['month','year'])
df



sale
month year      
1     2013    55
4     2014    33
7     2015   234
9     2016    56

multiindex

In [783]:
df.index

MultiIndex([(1, 2013),
            (4, 2014),
            (7, 2015),
            (9, 2016)],
           names=['month', 'year'])

`df.index.names` 返回当前 DataFrame 索引的名称列表。
如果 DataFrame 使用了 MultiIndex（多级索引），则会返回每一级索引的名称。
例如，对于一个具有两级索引的 DataFrame，`df.index.names` 可能返回 `['level_1', 'level_2']`。
这在需要查看或修改索引名称时非常有用。

In [784]:
df.index.names

FrozenList(['month', 'year'])

In [785]:
df.index.levels

FrozenList([[1, 4, 7, 9], [2013, 2014, 2015, 2016]])

In [786]:
arrays=[[1,1,2,2],['red','blue','red','blue']]
pd.MultiIndex.from_arrays(arrays,names=('number','color'))

MultiIndex([(1,  'red'),
            (1, 'blue'),
            (2,  'red'),
            (2, 'blue')],
           names=['number', 'color'])

索引

drop删除列

In [787]:
df=df.drop(['sale'],axis=1)
df

Empty DataFrame
Columns: []
Index: [(1, 2013), (4, 2014), (7, 2015), (9, 2016)]

`df=df.drop(['sale'],axis=1)` 删除了 DataFrame 中名为 `'sale'` 的列。
参数 `axis=1` 指定操作的是列，而不是行。
此操作返回一个新的 DataFrame，并不会修改原始 DataFrame，除非使用 `inplace=True` 参数。

直接索引（先列后行）

In [788]:
data['体育']['学生0']

41

loc和iloc

In [789]:
data

语文  数学  英语  政治  体育
学生0  76  99  73  99  41
学生1  53  76  65  76  53
学生2  79  98  42  87  56
学生3  51  87  43  61  82
学生4  44  44  86  61  97
学生5  85  88  40  68  81
学生6  52  72  95  82  56
学生7  78  59  77  62  80
学生8  55  44  59  65  63
学生9  62  82  41  89  97

In [790]:
data.loc[:,'语文':'数学']#只能通过行列索引名字

语文  数学
学生0  76  99
学生1  53  76
学生2  79  98
学生3  51  87
学生4  44  44
学生5  85  88
学生6  52  72
学生7  78  59
学生8  55  44
学生9  62  82

In [791]:
data.iloc[:3,:5]#通过索引下标

语文  数学  英语  政治  体育
学生0  76  99  73  99  41
学生1  53  76  65  76  53
学生2  79  98  42  87  56

ix

In [793]:
data.loc[data.index[0:4],['语文','体育']]

语文  体育
学生0  76  41
学生1  53  53
学生2  79  56
学生3  51  82

In [795]:
data.columns.get_indexer(['语文','体育'])

array([0, 4])

In [794]:
data.iloc[0:4,data.columns.get_indexer(['语文','体育'])]

语文  体育
学生0  76  41
学生1  53  53
学生2  79  56
学生3  51  82

`data.iloc[0:4,data.columns.get_indexer(['语文','体育'])]` 使用了 Pandas 的 `iloc` 方法和 `get_indexer` 方法来选择数据框中的特定行和列。

1. `data.iloc[0:4]` 表示选择数据框的第 0 到第 3 行（不包括第 4 行）。
2. `data.columns.get_indexer(['语文','体育'])` 返回列名 `'语文'` 和 `'体育'` 在数据框列索引中的位置。
3. 结合 `iloc` 和 `get_indexer`，可以通过列索引位置选择特定的列。

最终，这段代码返回数据框中第 0 到第 3 行的 `'语文'` 和 `'体育'` 列的数据。