In [481]:
import numpy as np
import pandas as pd

In [482]:
df=pd.DataFrame(data=np.random.randint(0,100,size=(5,4)),columns=list('ABCD'))
df

A   B   C   D
0  26  29   9  37
1  82  53   6  23
2  93  43  84  98
3  74  26  90   5
4  98  68  38  55

In [483]:
condition=df>60

In [484]:
condition=df['A']>60

In [485]:
df.where(cond=df>60,other='不及格')

A    B    C    D
0  不及格  不及格  不及格  不及格
1   82  不及格  不及格  不及格
2   93  不及格   84   98
3   74  不及格   90  不及格
4   98   68  不及格  不及格

### 代码 `df.where(cond=df>60,other='不及格')` 的解释

1. `df.where` 方法用于根据条件筛选数据。
2. 参数 `cond=df>60` 表示筛选条件：保留 `df` 中大于 60 的值。
3. 参数 `other='不及格'` 表示如果条件不满足，则将对应的值替换为 `'不及格'`。

总结：这段代码将 `df` 中大于 60 的值保留，小于或等于 60 的值替换为 `'不及格'`。

In [486]:
df['A']>60

0    False
1     True
2     True
3     True
4     True
Name: A, dtype: bool

满足条件保留

In [487]:
df.where(df['A']>60,other='不及格')

A    B    C    D
0  不及格  不及格  不及格  不及格
1   82   53    6   23
2   93   43   84   98
3   74   26   90    5
4   98   68   38   55

In [488]:
df.where(cond=df>60,other=pd.Series(data=[100,200],index=['A','B']),axis=1)

A    B     C     D
0  100  200   NaN   NaN
1   82  200   NaN   NaN
2   93  200  84.0  98.0
3   74  200  90.0   NaN
4   98   68   NaN   NaN

### 代码 `df.where(cond=df>60,other=pd.Series(data=[100,200],index=['A','B']),axis=1)` 的解释

1. `df.where` 方法用于根据条件筛选数据。
2. 参数 `cond=df>60` 表示筛选条件：保留 `df` 中大于 60 的值。
3. 参数 `other=pd.Series(data=[100,200],index=['A','B'])` 表示如果条件不满足，将替换为指定的值：
   - 列 `'A'` 替换为 `100`。
   - 列 `'B'` 替换为 `200`。
4. 参数 `axis=1` 表示按列进行操作。

总结：这段代码将 `df` 中大于 60 的值保留，而对于不满足条件的值，按列替换为指定的值（列 `'A'` 替换为 `100`，列 `'B'` 替换为 `200`）。

不满足条件保留

In [489]:
df.mask(df>60,other='及格')

A   B   C   D
0  26  29   9  37
1  及格  53   6  23
2  及格  43  及格  及格
3  及格  26  及格   5
4  及格  及格  38  55

In [490]:
df.mask(df>60,other=pd.Series(data=[100,200],index=['A','B']),axis=1)

A    B     C     D
0   26   29   9.0  37.0
1  100   53   6.0  23.0
2  100   43   NaN   NaN
3  100   26   NaN   5.0
4  100  200  38.0  55.0

In [491]:
df.query('A > 60 and B >60')

A   B   C   D
4  98  68  38  55

### 代码 `df.query('A > 60 and B >60')` 的解释

1. `df.query` 方法用于根据表达式筛选 DataFrame 中的行。
2. 表达式 `'A > 60 and B >60'` 表示筛选条件：
   - 列 `'A'` 的值大于 60。
   - 列 `'B'` 的值大于 60。
   - 两个条件同时满足（逻辑与）。

总结：这段代码筛选出 `df` 中列 `'A'` 和列 `'B'` 的值均大于 60 的行。

In [492]:
df.columns=['AA','BB','CB','DB']
df

AA  BB  CB  DB
0  26  29   9  37
1  82  53   6  23
2  93  43  84  98
3  74  26  90   5
4  98  68  38  55

In [493]:
df.filter(items=[0,1],axis=0)

AA  BB  CB  DB
0  26  29   9  37
1  82  53   6  23

### 代码 `df.filter(items=[0,1],axis=0)` 的解释

1. `df.filter` 方法用于根据指定的条件筛选 DataFrame 的行或列。
2. 参数 `items=[0,1]` 表示要筛选的索引值，这里是行索引 `0` 和 `1`。
3. 参数 `axis=0` 表示按行进行筛选。

总结：这段代码筛选出 `df` 中行索引为 `0` 和 `1` 的行。

In [494]:
df.filter(regex='B',axis=1)

BB  CB  DB
0  29   9  37
1  53   6  23
2  43  84  98
3  26  90   5
4  68  38  55

### 代码 `df.filter(regex='B',axis=1)` 的解释

1. `df.filter` 方法用于根据指定条件筛选 DataFrame 的行或列。
2. 参数 `regex='B'` 表示使用正则表达式匹配列名中包含 `'B'` 的列。
3. 参数 `axis=1` 表示按列进行筛选。

总结：这段代码筛选出 `df` 中列名包含 `'B'` 的所有列。

In [495]:
arr1=df.values
arr1

array([[26, 29,  9, 37],
       [82, 53,  6, 23],
       [93, 43, 84, 98],
       [74, 26, 90,  5],
       [98, 68, 38, 55]])

In [496]:
arr1.sum()

1037

In [497]:
arr1.mean(axis=0)

array([74.6, 43.8, 45.4, 43.6])

### 代码 `arr1.mean()` 的解释

1. `arr1` 是一个 NumPy 数组，存储了 DataFrame 的所有值。
2. `mean()` 方法用于计算数组中所有元素的平均值。

总结：这段代码计算并返回 `arr1` 数组中所有元素的平均值。

In [498]:
arr1.astype(np.float32)

array([[26., 29.,  9., 37.],
       [82., 53.,  6., 23.],
       [93., 43., 84., 98.],
       [74., 26., 90.,  5.],
       [98., 68., 38., 55.]], dtype=float32)

In [499]:
arr1 = arr1.astype(np.float64)  # Convert arr1 to a float array
arr1[1, 1] = np.nan

In [500]:
arr1

array([[26., 29.,  9., 37.],
       [82., nan,  6., 23.],
       [93., 43., 84., 98.],
       [74., 26., 90.,  5.],
       [98., 68., 38., 55.]])

In [501]:
arr1.sum()

nan

In [502]:
np.nansum(arr1)

984.0

In [503]:
import numpy as np  # Ensure numpy is imported

df.loc[1, 'BB'] = np.nan

### 代码 `df.loc[1, 'BB'] = np.nan` 的解释

1. `df.loc[1, 'BB']` 使用 `.loc` 方法定位 DataFrame 中第 1 行（索引为 `1`）和列 `'BB'` 的单元格。
2. `np.nan` 是 NumPy 中表示缺失值（NaN）的常量。
3. 这段代码将第 1 行列 `'BB'` 的值设置为缺失值（NaN）。

总结：这段代码在 DataFrame 中引入了一个缺失值，用于表示数据的空缺或不可用。

In [504]:
df.sum()#DatrFrame默认列方向集合
#pandas自动忽略空值

AA    373.0
BB    166.0
CB    227.0
DB    218.0
dtype: float64

In [505]:
np.nansum(df.values)

984.0