In [128]:
import numpy as np
arr=np.random.random(10)
arr

array([0.50189669, 0.28370277, 0.21805212, 0.3221231 , 0.2499655 ,
       0.81415029, 0.25372695, 0.60024864, 0.96993277, 0.4215054 ])

In [129]:
arr2=np.random.randint(0,10,size=10)
arr2

array([9, 4, 8, 5, 9, 8, 4, 4, 2, 2])

In [130]:
arr+arr2

array([9.50189669, 4.28370277, 8.21805212, 5.3221231 , 9.2499655 ,
       8.81415029, 4.25372695, 4.60024864, 2.96993277, 2.4215054 ])

In [131]:
arr2=np.random.randint(0,10,size=(3,3))
arr1=np.random.random(size=(3,3))
display(arr1,arr2)


array([[0.79888894, 0.99813596, 0.4889166 ],
       [0.33623932, 0.07202599, 0.0599452 ],
       [0.05748991, 0.21357428, 0.16955739]])

array([[6, 9, 9],
       [2, 4, 7],
       [2, 7, 4]])

In [132]:
arr1+arr2

array([[6.79888894, 9.99813596, 9.4889166 ],
       [2.33623932, 4.07202599, 7.0599452 ],
       [2.05748991, 7.21357428, 4.16955739]])

In [133]:
arr2>5#广播机制

array([[ True,  True,  True],
       [False, False,  True],
       [False,  True, False]])

In [134]:
a=np.ones((2,3))
b=np.arange(3)
display(a,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

In [135]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.]])

In [136]:
a=np.ones((4,3,2))
b=np.random.randint(0,10,size=(3,2))
display(a,b)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

array([[9, 7],
       [3, 9],
       [0, 8]])

In [137]:
a+b

array([[[10.,  8.],
        [ 4., 10.],
        [ 1.,  9.]],

       [[10.,  8.],
        [ 4., 10.],
        [ 1.,  9.]],

       [[10.,  8.],
        [ 4., 10.],
        [ 1.,  9.]],

       [[10.,  8.],
        [ 4., 10.],
        [ 1.,  9.]]])

In [138]:
a=np.arange(3).reshape((3,1))
b=np.arange(3)
display(a,b)

array([[0],
       [1],
       [2]])

array([0, 1, 2])

In [139]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 广播机制示例
在 `a+b` 中，`a` 是一个形状为 `(3,1)` 的二维数组，`b` 是一个形状为 `(3,)` 的一维数组。
通过 NumPy 的广播机制，`b` 的形状会被扩展为 `(3,1)`，然后与 `a` 逐元素相加。
广播机制允许形状不同的数组进行运算，只要它们在维度上是兼容的。

In [140]:
a+1

array([[1],
       [2],
       [3]])