In [3]:
import numpy as np

In [4]:
a=np.ones((4,1))
b=np.arange(4)
display(a,b)

array([[1.],
       [1.],
       [1.],
       [1.]])

array([0, 1, 2, 3])

In [5]:
a+b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

a=np.ones((4,1)),b=np.arange(4),a+b

### 广播机制示例
在 `a+b` 中，`a` 是一个形状为 `(4,1)` 的二维数组，`b` 是一个形状为 `(4,)` 的一维数组。
通过 NumPy 的广播机制，`b` 的形状会被扩展为 `(4,1)`，然后与 `a` 逐元素相加。
广播机制允许形状不同的数组进行运算，只要它们在维度上是兼容的。

假设有100个员工，每个人考勤天数-1，如何操作
