In [35]:
import numpy as np

In [36]:
np.random.random(size=10)[::-1]

array([0.72417411, 0.28686282, 0.99390308, 0.68235972, 0.26454106,
       0.54359426, 0.11138331, 0.63429197, 0.32954026, 0.05573902])

创建一个长度为10的随机数组，实现逆序输出

In [37]:
data2=np.random.randint(0,100,size=(5,4))
display(data2)


array([[66, 39, 74,  4],
       [36, 66, 95, 39],
       [55, 87,  3, 31],
       [47, 69, 24, 73],
       [66, 44, 89, 36]])

In [38]:
data2[:,[-2,-1]]

array([[74,  4],
       [95, 39],
       [ 3, 31],
       [24, 73],
       [89, 36]])

In [39]:
data2[:,-2:]

array([[74,  4],
       [95, 39],
       [ 3, 31],
       [24, 73],
       [89, 36]])

In [40]:
data2[:,[False,False,True,True]]

array([[74,  4],
       [95, 39],
       [ 3, 31],
       [24, 73],
       [89, 36]])

构造一个形状（5,4）的二维数组,提取最后两列，使用3种方法