In [383]:
import numpy   as np

In [384]:
data=np.random.randint(0,100,size=5)
data

array([45, 81, 24, 94, 70])

In [385]:
data.sum()

314

In [386]:
data=np.random.randint(0,10,size=(3,2))
data

array([[3, 2],
       [9, 2],
       [2, 0]])

In [387]:
data.sum()

18

In [388]:
data.sum(axis=0)#列

array([14,  4])

In [389]:
data.sum(axis=1)#行

array([ 5, 11,  2])

In [390]:
type(None)

NoneType

In [391]:
type(np.nan)

float

In [392]:
np.nan

nan

In [393]:
data=np.random.randint(0,10,size=10)
data

array([5, 8, 4, 8, 1, 8, 0, 8, 3, 4])

In [394]:
data.astype(np.float32)

array([5., 8., 4., 8., 1., 8., 0., 8., 3., 4.], dtype=float32)

In [395]:
data = data.astype(np.float64)  # Convert the array to float type
data[1] = np.nan  # Assign np.nan to the second element
data


array([ 5., nan,  4.,  8.,  1.,  8.,  0.,  8.,  3.,  4.])

In [396]:
data.sum()

nan

In [397]:
np.nansum(data)

41.0

In [398]:
arr=np.random.randint(0,10,size=10)
arr

array([5, 8, 6, 0, 5, 5, 9, 6, 9, 4])

In [399]:
arr.max()


9

In [400]:
arr.min()

0

In [401]:
data=np.random.randint(0,2,size=10).astype(bool)

In [402]:
data.any()#至少有一个True,返回True

True

In [403]:
data.all()#全是True,返回True

False

In [404]:
datal=np.array([True,False,True])
datal.all()

False

In [405]:
score=np.random.randint(0,100,size=100)
score

array([37, 74, 22, 51, 34, 52,  6, 39, 96, 80,  7, 33, 25, 92, 20, 59, 61,
       59, 27, 80, 21, 20, 20, 63, 89, 40, 59, 90,  8, 94, 70, 62, 68, 58,
       27, 46, 20, 66, 71, 44, 64, 55, 96, 91, 51, 72,  0, 15, 84, 55, 33,
       10, 96, 12, 26, 45, 29, 29, 26, 24, 64, 35, 35, 80, 32, 16, 28,  9,
       77, 86, 86, 17, 39, 39,  7, 47, 25, 33, 23, 60, 48, 69, 84, 51, 83,
       74, 41,  5, 95, 35, 35, 83, 40, 86, 42, 63, 35, 63, 44, 26])

In [406]:
(score<60).any()

True

In [407]:
(score>60).all()

False