In [191]:
import numpy as np

In [192]:
arr=[1,2,3,4,5]

In [193]:
arr2=np.random.randint(0,10,size=(4,3))
arr2

array([[3, 7, 9],
       [2, 2, 7],
       [0, 5, 9],
       [2, 1, 4]])

In [194]:
np.delete(arr,1)

array([1, 3, 4, 5])

In [195]:
np.delete(arr2,[[1,2]],axis=0)

array([[3, 7, 9],
       [2, 1, 4]])

In [196]:
arr=np.random.randint(0,10,size=8)
arr

array([2, 0, 1, 1, 9, 3, 6, 9])

In [197]:
arr.reshape((2,4),order='C')#不能显示使用shape
#C按行

array([[2, 0, 1, 1],
       [9, 3, 6, 9]])

In [198]:
arr.reshape((2,4),order='F')#按列

array([[2, 1, 9, 6],
       [0, 1, 3, 9]])

In [199]:
arr.reshape((2,4),order='A')#原顺序

array([[2, 0, 1, 1],
       [9, 3, 6, 9]])

In [200]:
for i in arr:
    print(i)

2
0
1
1
9
3
6
9


In [201]:
for arrl in arr2:
    for i in arrl:
        print(i)
    

3
7
9
2
2
7
0
5
9
2
1
4


In [202]:
for i in arr.flat:
    print(i)

2
0
1
1
9
3
6
9


`arr.flat` 是 NumPy 数组的一个迭代器属性，它会将多维数组“扁平化”为一维序列进行遍历。使用 `for i in arr.flat:` 可以逐个访问数组中的每一个元素，无论原数组的维度如何。这样可以方便地对数组中的所有元素进行操作，而无需关心其具体的形状结构。

In [203]:
np.ndarray.flat

<attribute 'flat' of 'numpy.ndarray' objects>

In [204]:
arr2

array([[3, 7, 9],
       [2, 2, 7],
       [0, 5, 9],
       [2, 1, 4]])

In [205]:
arr2.flatten()

array([3, 7, 9, 2, 2, 7, 0, 5, 9, 2, 1, 4])

`arr2.flatten()` 会将多维的 NumPy 数组 `arr2` 按行优先（C 顺序）展开为一个一维数组，并返回一个新的数组副本。无论原数组的形状如何，`flatten()` 都会生成一个全新的、连续存储的一维数组，原数组本身不会被修改。

In [206]:
arr2.ravel()

array([3, 7, 9, 2, 2, 7, 0, 5, 9, 2, 1, 4])

`arr2.ravel()` 也会将多维的 NumPy 数组 `arr2` 展开为一维数组，但与 `flatten()` 不同的是，`ravel()` 通常返回的是原数组的视图（view），不会产生数据的副本（除非有必要）。这意味着对 `ravel()` 返回结果的修改可能会影响原数组（如果返回的是视图）。`ravel()` 默认也是按行优先（C 顺序）展开。

In [207]:
arr2.shape

(4, 3)

In [208]:
arr2

array([[3, 7, 9],
       [2, 2, 7],
       [0, 5, 9],
       [2, 1, 4]])

In [209]:
arr2.transpose([1,0])#转置

array([[3, 2, 0, 2],
       [7, 2, 5, 1],
       [9, 7, 9, 4]])

`arr2.transpose([1, 0])` 会对二维数组 `arr2` 进行转置操作，将其行和列进行交换。参数 `[1, 0]` 指定了新的轴顺序：原来的第 1 轴（列）变为第 0 轴（行），原来的第 0 轴（行）变为第 1 轴（列）。这等价于 `arr2.T`，常用于矩阵运算或数据格式转换。