In [21]:
import numpy as np

In [22]:
a=np.ones((4,1))
b=np.arange(4)
display(a,b)

array([[1.],
       [1.],
       [1.],
       [1.]])

array([0, 1, 2, 3])

In [23]:
a+b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

a=np.ones((4,1)),b=np.arange(4),a+b

### 广播机制示例
在 `a+b` 中，`a` 是一个形状为 `(4,1)` 的二维数组，`b` 是一个形状为 `(4,)` 的一维数组。
通过 NumPy 的广播机制，`b` 的形状会被扩展为 `(4,1)`，然后与 `a` 逐元素相加。
广播机制允许形状不同的数组进行运算，只要它们在维度上是兼容的。

In [24]:
data=np.random.randint(20,23,size=100)
data

array([21, 21, 21, 20, 22, 21, 22, 21, 22, 21, 20, 22, 21, 21, 22, 20, 21,
       21, 22, 21, 20, 22, 22, 21, 21, 22, 20, 20, 22, 21, 20, 21, 22, 21,
       21, 22, 22, 20, 21, 21, 20, 21, 21, 21, 20, 21, 22, 21, 20, 22, 21,
       22, 22, 20, 20, 21, 22, 21, 20, 22, 21, 22, 20, 21, 22, 22, 20, 20,
       21, 22, 21, 20, 22, 21, 21, 21, 20, 20, 20, 21, 22, 21, 22, 20, 20,
       20, 21, 22, 20, 21, 20, 22, 21, 22, 21, 22, 21, 21, 21, 20])

In [25]:
data-1

array([20, 20, 20, 19, 21, 20, 21, 20, 21, 20, 19, 21, 20, 20, 21, 19, 20,
       20, 21, 20, 19, 21, 21, 20, 20, 21, 19, 19, 21, 20, 19, 20, 21, 20,
       20, 21, 21, 19, 20, 20, 19, 20, 20, 20, 19, 20, 21, 20, 19, 21, 20,
       21, 21, 19, 19, 20, 21, 20, 19, 21, 20, 21, 19, 20, 21, 21, 19, 19,
       20, 21, 20, 19, 21, 20, 20, 20, 19, 19, 19, 20, 21, 20, 21, 19, 19,
       19, 20, 21, 19, 20, 19, 21, 20, 21, 20, 21, 20, 20, 20, 19])

假设有100个员工，每个人考勤天数-1，如何操作


In [26]:
data=np.random.randint(7,10,size=100)
data

array([8, 8, 7, 8, 8, 7, 7, 7, 9, 8, 9, 8, 8, 9, 9, 9, 8, 9, 9, 7, 8, 8,
       9, 9, 7, 8, 8, 9, 8, 7, 8, 7, 8, 8, 7, 9, 8, 8, 7, 9, 8, 9, 8, 9,
       7, 8, 7, 8, 8, 8, 7, 8, 8, 9, 9, 8, 8, 9, 8, 8, 7, 9, 9, 9, 8, 7,
       8, 9, 7, 7, 9, 7, 9, 7, 8, 9, 8, 8, 9, 9, 9, 8, 8, 7, 9, 9, 8, 8,
       8, 8, 9, 9, 7, 7, 7, 8, 7, 8, 7, 7])

In [ ]:
data<8 

array([False, False,  True, False, False,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False,  True, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False,  True,  True, False,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True,  True,  True, False,  True, False,  True,
        True])

假设员工上班通过np.random.randint(7,10,100)获取，如何快速找到上班时间不足8小时的员工