In [160]:
import numpy as np


In [161]:
data=np.random.randint(0,100,size=10)

In [162]:
data

array([31, 32, 28, 12, 72,  9, 61, 52, 21, 96])

In [163]:
data.argmax()#最大值索引

9

In [164]:
data.argmin#最小值索引

<function ndarray.argmin>

In [165]:
data>60

array([False, False, False, False,  True, False,  True, False, False,
        True])

In [166]:
np.where(data>60)

(array([4, 6, 9]),)

In [167]:
arr=np.random.randint(0,10,size=8)
arr

array([5, 3, 1, 1, 7, 4, 2, 7])

In [168]:
np.sort(arr)

array([1, 1, 2, 3, 4, 5, 7, 7])

In [169]:
data=np.random.randint(0,10,size=5)
data

array([7, 4, 1, 4, 3])

In [170]:
np.argsort(data)

array([2, 4, 1, 3, 0])

`np.argsort(data)` 返回对数组 `data` 排序后各元素的索引数组。也就是说，结果中的每个值表示原数组中对应位置的元素在排序后应处于的位置。通过该索引数组，可以重建排序后的数组，或用于间接排序操作。

In [171]:
import random

In [172]:
data=np.random.permutation(10000)

`np.random.permutation(10000)` 会生成一个长度为 10000 的整数数组，包含从 0 到 9999 的所有整数，并将其随机打乱顺序。这样可以得到一个无重复元素且顺序随机的数组，常用于洗牌、随机抽样等场景。

In [173]:
data

array([3264, 9506, 1757, ..., 8154, 2392,  588])

In [174]:
np.partition(data,-2)[-2:]

array([9998, 9999])

`np.partition(data, -2)[-2:]` 用于快速找到数组 `data` 中最大的两个元素。`np.partition` 会将数组重新排列，使得第 -2（倒数第二）大的元素及其之后的元素（即最大的两个元素）排在数组的最后两位，但这两者之间不保证有序。通过 `[-2:]` 取出这两个最大值。

In [175]:
np.partition(data,2)[:2]


array([0, 1])

`np.partition(data, 2)` 会将数组 `data` 重新排列，使得最小的三个元素（即索引为 0、1、2 的元素）被移动到数组的前三个位置（但这三者之间不保证有序），其余元素顺序不确定。这样可以高效地找到数组中最小的几个元素。