In [161]:
import numpy as np

In [162]:
data=[1,2,3,4]

In [163]:
data.append(5)

In [164]:
data

[1, 2, 3, 4, 5]

In [165]:
arr=np.array(data)
arr

array([1, 2, 3, 4, 5])

In [166]:
np.append(arr,6)

array([1, 2, 3, 4, 5, 6])

In [167]:
arr2=np.random.randint(0,10,size=(4,3))
arr2

array([[0, 0, 9],
       [9, 0, 3],
       [2, 5, 0],
       [4, 6, 0]])

In [168]:
np.append(arr2, [[1], [2], [3], [4]], axis=1)

array([[0, 0, 9, 1],
       [9, 0, 3, 2],
       [2, 5, 0, 3],
       [4, 6, 0, 4]])

In [169]:
np.append(arr2, [[1, 2, 3]], axis=0)

array([[0, 0, 9],
       [9, 0, 3],
       [2, 5, 0],
       [4, 6, 0],
       [1, 2, 3]])

In [170]:
data=np.ones(shape=(4,1))
data

array([[1.],
       [1.],
       [1.],
       [1.]])

In [171]:
np.append(arr2,data,axis=1)

array([[0., 0., 9., 1.],
       [9., 0., 3., 1.],
       [2., 5., 0., 1.],
       [4., 6., 0., 1.]])

In [172]:
np.insert(arr,2,100)

array([  1,   2, 100,   3,   4,   5])

In [173]:
arr2

array([[0, 0, 9],
       [9, 0, 3],
       [2, 5, 0],
       [4, 6, 0]])

In [174]:
np.insert(arr2,2,[[1,1,1,1]],axis=1)

array([[0, 0, 1, 9],
       [9, 0, 1, 3],
       [2, 5, 1, 0],
       [4, 6, 1, 0]])

In [175]:
np.insert(arr2,2,[[1,1,1]],axis=0)

array([[0, 0, 9],
       [9, 0, 3],
       [1, 1, 1],
       [2, 5, 0],
       [4, 6, 0]])