In [88]:
import numpy as np

In [89]:
python=np.random.randint(0,100,size=100)

In [90]:
((python>60)*1).mean()

0.4

生成一个成绩列表，100人。求及格率

### 计算及格率
代码 `((python>60)*1).mean()` 的作用是计算成绩列表中及格的比例。
- `python>60` 会生成一个布尔数组，表示每个成绩是否大于 60（即是否及格）。
- `*1` 将布尔值转换为整数值（`True` 转为 1，`False` 转为 0）。
- `.mean()` 计算数组的平均值，即及格的比例（及格人数占总人数的百分比）。

In [91]:
def standerd_transform(x):
    return (x-x.mean())/x.std()
    

数据标准化：减去期望值再除以方差

### 数据标准化函数
函数 `standerd_transform(x)` 用于对输入数组 `x` 进行标准化处理。
- 标准化的公式为 `(x - x.mean()) / x.std()`。
- 该公式会将数据的均值调整为 0，标准差调整为 1，从而消除数据的量纲影响。
- 标准化后的数据适用于需要归一化输入的机器学习算法或统计分析。

In [92]:
data=np.random.randn(100)
data

array([-1.82142333e+00,  2.21153456e+00, -1.06996922e+00, -1.51546277e+00,
        1.22707918e-01,  8.44603114e-01, -8.22629087e-01, -2.04151016e+00,
       -2.03287080e+00, -1.45706005e-01, -2.27742763e+00,  4.86694328e-01,
        5.61248929e-01,  5.45304347e-01, -2.14383803e+00,  3.23973581e-01,
        1.54050249e+00,  1.03346688e+00, -1.66521221e+00,  3.80573887e-01,
       -1.27261373e+00,  9.57004646e-01,  3.49269169e-01, -1.02058418e+00,
       -2.06632323e+00,  2.03525343e-01, -2.36607716e-01, -1.36801429e+00,
       -1.82198483e-01,  3.82084067e-04,  9.40946080e-01,  1.26334018e+00,
       -8.38754136e-01,  3.62527134e-01,  5.05093526e-01,  1.94865312e-01,
        5.25382099e-01,  1.87108173e-01,  8.39677931e-01,  8.96641211e-01,
       -1.09499555e-01,  8.38651122e-01, -6.87444922e-01,  1.04538330e+00,
       -4.46691334e-01, -1.05445969e+00,  2.81722855e-01,  6.14983861e-01,
        2.13457152e-01, -3.38122012e-01,  2.79308834e-01,  1.28475972e+00,
       -3.60089335e-01, -

随机一个一维数组，比较其中是否有至少一个数据大于3倍平均值

In [93]:
data=np.random.randn(1000,3)
data

array([[ 0.71163693, -0.98335778,  1.85278326],
       [-0.90802833,  0.45837522,  1.29920697],
       [ 1.27135906, -0.49771876,  0.21689141],
       ...,
       [ 0.83397483,  0.56834744, -0.33214933],
       [ 0.22397298, -0.78911035,  1.34699061],
       [ 1.0624995 , -1.53912234, -0.06205021]])

In [94]:
(data>data.std(axis=0)*3).any(axis=0)

array([ True,  True, False])

生成1000行3列的一个标准正太分布方程组，查询每一列是否存在至少一个大数据大于该列的3倍标准差

### 检查是否存在异常值
代码 `(data>data.std(axis=0)*3).any(axis=0)` 用于检查数组 `data` 中每一列是否存在至少一个值大于该列标准差的 3 倍。
- `data.std(axis=0)` 计算每一列的标准差。
- `data>data.std(axis=0)*3` 生成一个布尔数组，表示每个元素是否大于对应列标准差的 3 倍。
- `.any(axis=0)` 检查布尔数组中每列是否至少有一个 `True` 值，返回一个布尔数组，表示每列是否存在异常值。
- 该操作常用于检测数据中的异常值（outliers）。

### 按列计算标准差
代码 `data.std(axis=0)` 用于计算数组 `data` 中每一列的标准差。
- 参数 `axis=0` 指定沿着第 0 轴（即行的方向）计算标准差，因此结果是一个包含每列标准差的一维数组。
- 标准差是衡量数据分布离散程度的指标，表示数据点与均值的平均偏离程度。
- 该操作常用于分析多维数据中各列的分布特性。

In [95]:
a=np.ones(shape=(4,4))
b=np.ones(shape=(4,4))
(a==b).all()

True

如何检查两个形状相同的数组完全一致

In [ ]:
c=np.array([1,1,1,2,3,4,4,5])


In [ ]:
np.unique(c)

### 去除重复值
使用 `np.unique(c)` 方法可以去除数组 `c` 中的重复值。
- 该方法返回一个排序后的新数组，其中包含原数组中所有唯一值。
- 常用于数据去重或统计唯一值的场景。