In [23]:
import numpy as np


In [24]:
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [25]:
type(a1)

numpy.ndarray

In [26]:
a1.ndim

1

维度

In [27]:
a1.size

3

元素个数

In [28]:
a1.dtype

dtype('int64')

数据类型

In [29]:
a2=np.array([[1,2,3],[2,3,4]])
print(a2)

[[1 2 3]
 [2 3 4]]


In [30]:
a2.ndim,a2.shape,a2.size,a2.dtype

(2, (2, 3), 6, dtype('int64'))

维度，形状，大小，类型

In [31]:
print(a2)

[[1 2 3]
 [2 3 4]]


In [32]:
display(a2)

array([[1, 2, 3],
       [2, 3, 4]])

In [33]:
print(a1,a2)

[1 2 3] [[1 2 3]
 [2 3 4]]


In [34]:
display(a1,a2)

array([1, 2, 3])

array([[1, 2, 3],
       [2, 3, 4]])

In [35]:
a2

array([[1, 2, 3],
       [2, 3, 4]])