In [45]:
import numpy as np

In [46]:
a1=np.random.randint(0,10,size=(3,4))
a2=np.random.randint(10,20,size=(3,4))
display(a1,a2)

array([[9, 7, 2, 6],
       [7, 1, 7, 3],
       [1, 0, 8, 5]])

array([[14, 14, 17, 14],
       [17, 19, 10, 14],
       [12, 18, 17, 15]])

In [47]:
np.concatenate((a1,a2),axis=0)#NumPy 中用于连接（拼接）数组的函数。

array([[ 9,  7,  2,  6],
       [ 7,  1,  7,  3],
       [ 1,  0,  8,  5],
       [14, 14, 17, 14],
       [17, 19, 10, 14],
       [12, 18, 17, 15]])

In [48]:
a3=np.random.randint(20,30,size=(3,3))
a3

array([[23, 29, 21],
       [28, 21, 24],
       [23, 22, 23]])

维度和级联的维度上长度一致

In [49]:
np.concatenate((a1,a3),axis=1)

array([[ 9,  7,  2,  6, 23, 29, 21],
       [ 7,  1,  7,  3, 28, 21, 24],
       [ 1,  0,  8,  5, 23, 22, 23]])

In [50]:
np.vstack((a1,a2))#竖着连

array([[ 9,  7,  2,  6],
       [ 7,  1,  7,  3],
       [ 1,  0,  8,  5],
       [14, 14, 17, 14],
       [17, 19, 10, 14],
       [12, 18, 17, 15]])

In [51]:
np.hstack((a1,a3))#横着连

array([[ 9,  7,  2,  6, 23, 29, 21],
       [ 7,  1,  7,  3, 28, 21, 24],
       [ 1,  0,  8,  5, 23, 22, 23]])

In [52]:
arr=np.random.randint(0,100,size=(6,5))
arr

array([[41, 16, 81, 76,  0],
       [45, 58, 93, 47,  5],
       [84, 81,  1, 18, 81],
       [35, 50, 61,  2, 61],
       [45, 38, 55, 10, 35],
       [83, 36, 30, 20, 31]])

In [53]:
np.split(arr,indices_or_sections=2,axis=0)# NumPy 中用于分割数组的函数。indices_or_sections表示要将数组沿指定轴均匀分割成多少个子数组

[array([[41, 16, 81, 76,  0],
        [45, 58, 93, 47,  5],
        [84, 81,  1, 18, 81]]),
 array([[35, 50, 61,  2, 61],
        [45, 38, 55, 10, 35],
        [83, 36, 30, 20, 31]])]

In [54]:
np.split(arr,indices_or_sections=[2,3],axis=1)#左闭右开区间

[array([[41, 16],
        [45, 58],
        [84, 81],
        [35, 50],
        [45, 38],
        [83, 36]]),
 array([[81],
        [93],
        [ 1],
        [61],
        [55],
        [30]]),
 array([[76,  0],
        [47,  5],
        [18, 81],
        [ 2, 61],
        [10, 35],
        [20, 31]])]

### 数组切分
使用 `np.split(arr,indices_or_sections=[2,3],axis=1)` 将数组 `arr` 沿列方向（`axis=1`）切分。
参数 `indices_or_sections=[2,3]` 指定切分点，将数组分为三部分：
- 第一部分包含前两列。
- 第二部分包含第 3 列。
- 第三部分包含剩余的列。