In [1]:
import numpy as np

In [2]:
python=np.random.randint(0,100,size=100)

In [3]:
((python>60)*1).mean()

0.52

生成一个成绩列表，100人。求及格率

### 计算及格率
代码 `((python>60)*1).mean()` 的作用是计算成绩列表中及格的比例。
- `python>60` 会生成一个布尔数组，表示每个成绩是否大于 60（即是否及格）。
- `*1` 将布尔值转换为整数值（`True` 转为 1，`False` 转为 0）。
- `.mean()` 计算数组的平均值，即及格的比例（及格人数占总人数的百分比）。

In [4]:
def standerd_transform(x):
    return (x-x.mean())/x.std()
    

数据标准化：减去期望值再除以方差

### 数据标准化函数
函数 `standerd_transform(x)` 用于对输入数组 `x` 进行标准化处理。
- 标准化的公式为 `(x - x.mean()) / x.std()`。
- 该公式会将数据的均值调整为 0，标准差调整为 1，从而消除数据的量纲影响。
- 标准化后的数据适用于需要归一化输入的机器学习算法或统计分析。

In [5]:
data=np.random.randn(100)
data

array([ 0.19112848,  1.16407153, -0.67536123, -1.61746217, -0.78291233,
        0.70024977,  0.94848091,  0.61900324,  0.99124531,  0.34216539,
        0.29078829,  1.86425581,  0.00655689,  0.26076728, -1.70703951,
       -0.27347444,  0.49092408, -0.82836376,  0.11058009,  1.75223597,
        0.15464491,  0.99206464,  0.00387052, -0.43704089,  0.54579907,
       -0.61620382,  0.32223619,  0.65050476, -1.10459054, -0.24979704,
       -0.21930002, -0.03149619,  1.43688221, -0.35168861,  0.71516655,
       -0.46475428, -0.66554535,  0.67708952,  0.86388712, -0.98148862,
        1.79196997,  0.45625658, -1.06249317,  0.02417476,  0.48058756,
       -0.75195491,  2.96588123,  0.75923967,  1.19627482,  1.1616542 ,
        1.99268508, -1.53921834, -0.00999454,  0.03588547, -1.96886201,
        0.02392235, -1.0121263 ,  2.15601159,  1.8866116 , -0.6499955 ,
       -0.37259491,  1.0122694 ,  1.57470627, -1.19234421, -1.02852602,
       -0.15056069, -2.05024824,  1.54986597, -0.79095718,  2.08

随机一个一维数组，比较其中是否有至少一个数据大于3倍平均值

In [6]:
data=np.random.randn(1000,3)
data

array([[-0.81473879, -0.08744495, -0.13781687],
       [-0.45362162,  0.06251745, -0.09549354],
       [-0.02990215, -0.15833496, -0.15658932],
       ...,
       [ 0.30328299, -0.59672283, -0.93750492],
       [ 0.62194472, -0.01579409,  1.42174951],
       [-0.56650791, -0.17702221,  0.64126323]])

In [7]:
(data>data.std(axis=0)*3).any(axis=0)

array([ True,  True,  True])

生成1000行3列的一个标准正太分布方程组，查询每一列是否存在至少一个大数据大于该列的3倍标准差

### 检查是否存在异常值
代码 `(data>data.std(axis=0)*3).any(axis=0)` 用于检查数组 `data` 中每一列是否存在至少一个值大于该列标准差的 3 倍。
- `data.std(axis=0)` 计算每一列的标准差。
- `data>data.std(axis=0)*3` 生成一个布尔数组，表示每个元素是否大于对应列标准差的 3 倍。
- `.any(axis=0)` 检查布尔数组中每列是否至少有一个 `True` 值，返回一个布尔数组，表示每列是否存在异常值。
- 该操作常用于检测数据中的异常值（outliers）。

### 按列计算标准差
代码 `data.std(axis=0)` 用于计算数组 `data` 中每一列的标准差。
- 参数 `axis=0` 指定沿着第 0 轴（即行的方向）计算标准差，因此结果是一个包含每列标准差的一维数组。
- 标准差是衡量数据分布离散程度的指标，表示数据点与均值的平均偏离程度。
- 该操作常用于分析多维数据中各列的分布特性。

In [8]:
a=np.ones(shape=(4,4))
b=np.ones(shape=(4,4))
(a==b).all()

True

如何检查两个形状相同的数组完全一致

In [9]:
c=np.array([1,1,1,2,3,4,4,5])


In [10]:
c=np.unique(c)
c

array([1, 2, 3, 4, 5])

### 去除重复值
使用 `np.unique(c)` 方法可以去除数组 `c` 中的重复值。
- 该方法返回一个排序后的新数组，其中包含原数组中所有唯一值。
- 常用于数据去重或统计唯一值的场景。