In [75]:
import numpy as np
arr=np.random.randint(0,100,size=(6,5))
arr

array([[25, 10, 25, 46, 83],
       [81, 90, 18, 82, 98],
       [51, 16, 53, 24, 81],
       [48, 27, 49, 16, 33],
       [88, 12, 65, 26, 74],
       [74, 89, 44, 34, 86]])

In [76]:
np.vsplit(arr,indices_or_sections=2)

[array([[25, 10, 25, 46, 83],
        [81, 90, 18, 82, 98],
        [51, 16, 53, 24, 81]]),
 array([[48, 27, 49, 16, 33],
        [88, 12, 65, 26, 74],
        [74, 89, 44, 34, 86]])]

### 垂直切分数组
使用 `np.vsplit(arr,indices_or_sections=2)` 将数组 `arr` 沿行方向（垂直）切分。
参数 `indices_or_sections=2` 表示将数组均匀分为两部分。
每部分包含相同数量的行，适用于行数可以被均匀分割的情况。

In [77]:
np.hsplit(arr,indices_or_sections=[2,3])

[array([[25, 10],
        [81, 90],
        [51, 16],
        [48, 27],
        [88, 12],
        [74, 89]]),
 array([[25],
        [18],
        [53],
        [49],
        [65],
        [44]]),
 array([[46, 83],
        [82, 98],
        [24, 81],
        [16, 33],
        [26, 74],
        [34, 86]])]

### 水平切分数组
使用 `np.hsplit(arr,indices_or_sections=[2,3])` 将数组 `arr` 沿列方向（水平）切分。
参数 `indices_or_sections=[2,3]` 指定切分点，将数组分为三部分：
- 第一部分包含前两列。
- 第二部分包含第 3 列。
- 第三部分包含剩余的列。

In [78]:
a1=np.random.randint(0,10,size=(4,4))
a2=np.random.randint(0,10,size=(8,4))
display(a1,a2)

array([[6, 9, 1, 0],
       [9, 9, 6, 0],
       [9, 9, 9, 1],
       [2, 3, 8, 9]])

array([[1, 3, 4, 6],
       [8, 9, 5, 9],
       [9, 0, 9, 8],
       [8, 5, 6, 9],
       [5, 5, 8, 7],
       [1, 7, 1, 5],
       [0, 0, 5, 9],
       [4, 4, 7, 6]])

In [79]:
np.concatenate((a1,a2),axis=0)

array([[6, 9, 1, 0],
       [9, 9, 6, 0],
       [9, 9, 9, 1],
       [2, 3, 8, 9],
       [1, 3, 4, 6],
       [8, 9, 5, 9],
       [9, 0, 9, 8],
       [8, 5, 6, 9],
       [5, 5, 8, 7],
       [1, 7, 1, 5],
       [0, 0, 5, 9],
       [4, 4, 7, 6]])

In [80]:
arr3=np.vstack((a1,a2))

生成两个形状分别为（4,4）和（8,4）的二维数组，尝试级联

In [81]:
np.split(arr3,indices_or_sections=3)

[array([[6, 9, 1, 0],
        [9, 9, 6, 0],
        [9, 9, 9, 1],
        [2, 3, 8, 9]]),
 array([[1, 3, 4, 6],
        [8, 9, 5, 9],
        [9, 0, 9, 8],
        [8, 5, 6, 9]]),
 array([[5, 5, 8, 7],
        [1, 7, 1, 5],
        [0, 0, 5, 9],
        [4, 4, 7, 6]])]

In [82]:
np.split(arr3,indices_or_sections=[4,8])

[array([[6, 9, 1, 0],
        [9, 9, 6, 0],
        [9, 9, 9, 1],
        [2, 3, 8, 9]]),
 array([[1, 3, 4, 6],
        [8, 9, 5, 9],
        [9, 0, 9, 8],
        [8, 5, 6, 9]]),
 array([[5, 5, 8, 7],
        [1, 7, 1, 5],
        [0, 0, 5, 9],
        [4, 4, 7, 6]])]

尝试用两种方法将上题级联结果保存并拆分成3等分

In [83]:
data=np.random.randint(0,10,size=5)

In [84]:
type(data)

numpy.ndarray

In [85]:
data.dtype

dtype('int64')

In [86]:
data.astype(np.float32)

array([4., 1., 6., 0., 9.], dtype=float32)

生成长度为5的整形数组，将类型修改为float32

### 修改数组数据类型
使用 `data.astype(np.float32)` 方法将数组 `data` 的数据类型从整型转换为 `float32` 类型。
该方法不会修改原数组，而是返回一个新的数组，且新数组的元素类型为 `float32`。
这种转换在需要更高精度或特定数据类型的计算场景中非常有用。