In [15]:
import numpy as np

In [16]:
np.random.randint(-5,5,size=(3,4))

array([[-4, -2,  0,  3],
       [ 4,  4, -4, -4],
       [-4, -1,  1, -2]])

创建一个（3,4）的二维数组，取值范围（-5,5）

In [17]:
np.linspace(0,15,5,endpoint=False)

array([ 0.,  3.,  6.,  9., 12.])

In [18]:
np.arange(0,15,step=3)

array([ 0,  3,  6,  9, 12])

创建一组等差数列,步长为3，数组长度为5.

In [19]:
data=np.random.random(size=(100,100,3))
data.dtype

dtype('float64')

构造一个3维取值范围0-1的随机数组，数组类型为np.float64，形状为(100,100,3)

In [20]:
np.linspace(0,2*np.pi,num=8,endpoint=False)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714])

已知π在numpy中是预制的常量,可以用np.pi访问，计算出一个圆等分成8份的代码